services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite -l /data -s --blobHost 0.0.0.0 --queueHost 0.0.0.0"
    ports:
      - "10000:10000" # blob
      - "10001:10001" # queue
      - "10002:10002" # table
    volumes: ["azurite_data:/data"]
volumes:
  mongo_data:
  azurite_data:
